server:
  port: "8080"
  mode: "debug"
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"

database:
  host: "localhost"
  port: 5432
  user: "csms_user"
  password: "123456"
  dbname: "csms"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10

jwt:
  secret: "your-super-secret-jwt-key-change-this-in-production"
  expiration: "24h"
  issuer: "csms"

logging:
  level: "info"
  format: "json"
  output: "stdout"

monitoring:
  enabled: true
  port: "9090" 

tariff:
  price_per_kwh: 2500