/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ChartLine: typeof import('./src/components/charts/ChartLine.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    RemoteCommandPanel: typeof import('./src/components/common/RemoteCommandPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/common/StatCard.vue')['default']
    StatusIndicator: typeof import('./src/components/common/StatusIndicator.vue')['default']
    TableChargePoints: typeof import('./src/components/tables/TableChargePoints.vue')['default']
    TableIdTags: typeof import('./src/components/tables/TableIdTags.vue')['default']
    TableTransactions: typeof import('./src/components/tables/TableTransactions.vue')['default']
    TableUsers: typeof import('./src/components/tables/TableUsers.vue')['default']
    TagStatusSelector: typeof import('./src/components/common/TagStatusSelector.vue')['default']
  }
}
